jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOCKER_HOST: tcp://localhost:2375
      DOCKER_TLS_CERTDIR: ""
    steps:
      - name: Set up Docker DinD
        run: |
          dockerd --host=tcp://0.0.0.0:2375 --host=unix:///var/run/docker.sock &
          sleep 20

      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t vulnerable-app:latest .

      - name: Run vulnerable app container
        run: |
          docker run -d -p 3000:3000 --name vulnapp vulnerable-app:latest
          sleep 15

      - name: Check app availability
        run: curl -I http://localhost:3000

      - name: Stop and remove container
        run: |
          docker stop vulnapp
          docker rm vulnapp
