name: DevSecOps Pipeline

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  devsecops:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      # SCA: npm audit
      - name: Run SCA scan (npm audit)
        run: |
          if [ -f package.json ]; then
            npm install
            npm audit --audit-level=high || true
          fi
        continue-on-error: true

      # SAST: Semgrep
      - name: Run SAST scan (Semgrep)
        uses: returntocorp/semgrep-action@v1
        with:
          config: "p/default"
        continue-on-error: true

      # Secrets scan (Gitleaks)
      - name: Run Secrets scan (Gitleaks)
        uses: gitleaks/gitleaks-action@v2
        with:
          args: "--no-git -v"
        continue-on-error: true

      # Build Docker image
      - name: Build Docker image
        run: docker build -t vulnapp:latest .

      # Create Docker network
      - name: Create docker network
        run: docker network create juice-net || true

      # Run vulnerable app container in custom network
      - name: Run vulnerable app container
        run: |
          docker run -d --net juice-net --name vulnapp vulnapp:latest
          sleep 15

      # Check app availability
      - name: Check app availability
        run: curl -I http://localhost:3000 || exit 1
        continue-on-error: true

      # Docker login to Docker Hub
      - name: Docker Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Run OWASP ZAP DAST scan in the same network
      - name: Run DAST scan (OWASP ZAP)
        run: |
          mkdir -p zap-output
          docker run --rm --net juice-net \
            -v $(pwd)/zap-output:/zap/wrk/:rw \
            owasp/zaproxy/zap2docker-stable zap-baseline.py \
            -t http://vulnapp:3000 \
            -r zap_report.html || true

      # Upload ZAP report artifact
      - name: Upload ZAP report
        uses: actions/upload-artifact@v4
        with:
          name: zap-report
          path: zap-output/zap_report.html

      # Stop and remove container and network
      - name: Stop and remove container
        run: |
          docker stop vulnapp
          docker rm vulnapp
          docker network rm juice-net || true
